---
# roles/nso/tasks/main.xml

- name: copy nso images, sm package, and device inventory
  include: "nso_copy_images.yml"
  tags: nso_copy_images

# install nso
- name: install nso
  include: "nso_install.yml"
  tags: nso_install

# install ned and service packages
- name: install ned and service packages
  include: "nso_install_packages.yml"
  tags: nso_install_package

# start nso with package reload
- name: start nso application
  include: "nso_start.yml"
  tags: nso_start.yml

# load device inventory, devices and sync master
- name: add devices
  include: "nso_add_devices.yml"
  tags: nso_add_devices

# postcheck nso
- name: post check
  include: "nso_postcheck.yml"
  tags: nso_postcheck

