---
#file: roles/nso/tasks/nso_start.yml

- name: stop nso
  shell: "source {{ nso_install_path}}/ncsrc;{{ nso_install_path }}/bin/ncs --stop"
  ignore_errors: yes

- name: start nso
  shell: " source {{ nso_install_path}}/ncsrc;{{ nso_install_path }}/bin/ncs  --with-package-reload --cd {{ansible_env.HOME}}/ncs-run"
  