---
#file: roles/nso/tasks/nso_postcheck.yml

- include_vars:
    file: vars/labuser

- name: check device sync status
  shell: "source {{ nso_install_path}}/ncsrc;sh {{ansible_env.HOME}}/scripts/check-sync.sh master"
  register: syncoutput

- debug:
    msg: "device sync result: {{syncoutput.stdout}}"

- name: test python scripts runs on master
  shell: "source {{ nso_install_path}}/ncsrc; sh {{ansible_env.HOME}}/scripts/test-python-scripts.sh master {{labuser}}"
  register: pythontestoutput
- debug:
    msg: "python test: {{pythontestoutput.stdout}}"