---
#roles/nso/tasks/nso_install_packages.yml

- name: clean packages directory
  block:
    - file:
        path: "{{ nso_run_dir }}/packages"
        state: absent

    - file:
        path: "{{ nso_run_dir }}/packages"
        state: directory

- name: link unix bind ned
  file:
    path: "{{ nso_run_dir }}/packages/{{ ned_file }}"
    src: "{{ nso_image_path }}/{{ ned_file }}"
    state: "link"
    mode: "0444"

- name: install service model packages
  unarchive: 
    src: "{{ nso_src_dir }}/{{ item }}"
    dest: "{{ nso_run_dir }}/packages/"
  with_items:
    - "{{ dns_manager_pkg }}"
    - "{{ inventory_pkg }}"
